workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.nexa.gymmatch
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Clean CocoaPods cache and force fresh install
        script: |
          echo "🧹 Cleaning iOS Pod environment..."
          cd ios
          rm -rf Podfile.lock Pods
          pod install --repo-update
          cd ..
          echo "✅ Pod environment cleanup and update completed"
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      # - name: Flutter analyze
      #   script: |
      #     flutter analyze
      - name: Create export options plist
        script: |
          cat > $HOME/export_options.plist << EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>uploadBitcode</key>
            <false/>
            <key>compileBitcode</key>
            <false/>
            <key>uploadSymbols</key>
            <true/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>teamID</key>
            <string>7V5DA99X2M</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>com.nexa.gymmatch</key>
              <string>GYM MATCH App Store Profile</string>
            </dict>
          </dict>
          </plist>
          EOF
      - name: Flutter build ipa and automatically codesign using Codemagic cloud signing
        script: |
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=1 \
            --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - aka209859@gmail.com
        notify:
          success: true
          failure: true
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Internal Testers
      #   submit_to_app_store: false
