// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web Platform Configuration (GYM MATCH Production)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwD-_fz9m4vSQsbdXuQpKtbHguIl4LaM',
    appId: '1:506175392633:web:046d7c7a6a8ac7e606fda8',
    messagingSenderId: '506175392633',
    projectId: 'gym-match-e560d',
    authDomain: 'gym-match-e560d.firebaseapp.com',
    storageBucket: 'gym-match-e560d.firebasestorage.app',
    measurementId: 'G-DXGP9WX0Z8',
  );

  // Android Platform Configuration (後で本番設定に置き換え)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoAndroid-FitSync-Key-Replace-With-Real',
    appId: '1:123456789:android:abcdef123456',
    messagingSenderId: '123456789',
    projectId: 'fitsync-demo',
    storageBucket: 'fitsync-demo.appspot.com',
  );

  // iOS Platform Configuration (GYM MATCH Production - 暫定設定)
  // TODO: Firebase ConsoleからiOS用GoogleService-Info.plistを取得し正式設定に置き換え
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwD-_fz9m4vSQsbdXuQpKtbHguIl4LaM',  // Web設定を流用
    appId: '1:506175392633:ios:TEMP-iOS-AppID',        // 暫定iOS App ID
    messagingSenderId: '506175392633',
    projectId: 'gym-match-e560d',  // ✅ 正しいプロジェクトID
    storageBucket: 'gym-match-e560d.firebasestorage.app',
    iosBundleId: 'jp.nexa.fitsync',
  );

  // macOS Platform Configuration (GYM MATCH Production - 暫定設定)
  // TODO: Firebase ConsoleからmacOS用設定を取得し正式設定に置き換え
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYwD-_fz9m4vSQsbdXuQpKtbHguIl4LaM',  // Web設定を流用
    appId: '1:506175392633:macos:TEMP-macOS-AppID',    // 暫定macOS App ID
    messagingSenderId: '506175392633',
    projectId: 'gym-match-e560d',  // ✅ 正しいプロジェクトID
    storageBucket: 'gym-match-e560d.firebasestorage.app',
    iosBundleId: 'jp.nexa.fitsync',
  );
}
