// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.android:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are only configured for iOS, macOS, and Web platforms.',
        );
    }
  }

  // Web Platform Configuration (GYM MATCH Production)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYwD-_fz9m4vSQsbdXuQpKtbHguIl4LaM',
    appId: '1:506175392633:web:046d7c7a6a8ac7e606fda8',
    messagingSenderId: '506175392633',
    projectId: 'gym-match-e560d',
    authDomain: 'gym-match-e560d.firebaseapp.com',
    storageBucket: 'gym-match-e560d.firebasestorage.app',
    measurementId: 'G-DXGP9WX0Z8',
  );

  // Android Platform Configuration - Not supported (iOS専用アプリ)
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDYwD-_fz9m4vSQsbdXuQpKtbHguIl4LaM',
  //   appId: '1:506175392633:android:78f4e12b34567890fda8',
  //   messagingSenderId: '506175392633',
  //   projectId: 'gym-match-e560d',
  //   storageBucket: 'gym-match-e560d.firebasestorage.app',
  // );

  // iOS Platform Configuration (GYM MATCH Production - 正式設定)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFVfcWzXDTtc9Rk3Zr5OGRx63FXpMAHqY',
    appId: '1:506175392633:ios:50f4190f1047758206fda8',
    messagingSenderId: '506175392633',
    projectId: 'gym-match-e560d',
    storageBucket: 'gym-match-e560d.firebasestorage.app',
    iosBundleId: 'com.nexa.gymmatch',
  );

  // macOS Platform Configuration (GYM MATCH Production - iOS設定を流用)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFVfcWzXDTtc9Rk3Zr5OGRx63FXpMAHqY',
    appId: '1:506175392633:ios:50f4190f1047758206fda8',
    messagingSenderId: '506175392633',
    projectId: 'gym-match-e560d',
    storageBucket: 'gym-match-e560d.firebasestorage.app',
    iosBundleId: 'com.nexa.gymmatch',
  );
}
